### ISSUE TITLE
so what is the api_end_point.env file

### ISSUE THREAD

**Issue by marshalcn** [FresherDuong/AndroidFaceNetMobileForThesis#1]
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/LearnerDrivingCentre/Config/api_end_point.env: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)

**Comment by duongdinh98** [comment]
Sorry, my app needs back-end to use fully features, "api_end_point.env" is the back-end configuration file contained web server hostname. I will public all back-end code later.

**Comment by marshalcn** [comment]
> Sorry, my app needs back-end to use fully features, "api_end_point.env" is the back-end configuration file contained web server hostname. I will public all back-end code later.

ok
